#!/bin/sh -e
IFS= read -r -p 'Please enter blog password: ' PASSWORD
exec emacs -nw -Q -L /usr/share/emacs/site-lisp/org-mode -L . -l ert -l org-blog --eval "(setq org-blog-test-password \"${PASSWORD}\")" --eval '(ert t)'
